Event_Hall/Event_Hall/Models/AttendeeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Event_Hall.Models
{
    public class AttendeeModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Email { get; set; }
        [Required]
        public int Phone { get; set; }
        public string Field { get; set; }

        public EventModel Event { get; set; }
        public int EventId { get; set; }
    }
}

Event_Hall/Event_Hall/Models/ErrorViewModel.cs
using System;

namespace Event_Hall.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Event_Hall/Event_Hall/Models/EventModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Event_Hall.Models
{
    public class EventModel
    {
            public int Id { get; set; }
            [Required]
            public string Name { get; set; }
            public string Description { get; set; }
            [Required]
            public string Time { get; set; }
            public string Duration { get; set; }
            public string Image { get; set; }
            public List<AttendeeModel> Attendees { get; set; }

            public PresentorModel Presentor { get; set; }
            public int PresentorId { get; set; }

            public string PresentorName { get; set; }

            public HallModel Hall { get; set; }

            public int HallId { get; set; }
    }
    }

Event_Hall/Event_Hall/Models/HallModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Event_Hall.Models
{
    public class HallModel
    {
        public int Id { get; set; }
        [Required]
        public int Capacity { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public bool Avaliability { get; set; }
        public List<AttendeeModel> Event { get; set; }
    }
}

Event_Hall/Event_Hall/Models/PresentorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Event_Hall.Models
{
    public class PresentorModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Email { get; set; }
        [Required]
        public int Phone { get; set; }
        public string Field { get; set; }

        public List<EventModel> Events { get; set; }

    }
}

Event_Hall/Event_Hall/Controllers/AttendeesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Event_Hall.Data;

namespace Event_Hall.Controllers
{
    public class AttendeesController : Controller
    {
        private readonly AppDbContext _db;

        public AttendeesController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            var DbAttendees = _db.Attendees.ToList();
            ViewBag.Attendees = DbAttendees;
            return View();
        }
    }
}

Event_Hall/Event_Hall/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Event_Hall.Data;
using Microsoft.EntityFrameworkCore;

namespace Event_Hall.Controllers
{
    public class EventsController : Controller
    {
        private readonly AppDbContext _db;

        public EventsController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            var DbEvents = _db.Events.ToList();
            ViewBag.Events = DbEvents;
            return View();
        }
    }
}

Event_Hall/Event_Hall/Controllers/HallsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Event_Hall.Data;

namespace Event_Hall.Controllers
{
    public class HallsController : Controller
    {
        private readonly AppDbContext _db;

        public HallsController(AppDbContext context)
        {
            _db = context;
        }
        public IActionResult Index()
        {
            var DbHalls = _db.Halls.ToList();
            ViewBag.Halls = DbHalls;
            return View();
        }
    }
}

Event_Hall/Event_Hall/Controllers/HomeController.cs
using Event_Hall.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Event_Hall.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Event_Hall/Event_Hall/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Events Hall Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: black">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: mintcream">
            <div class="container" style="margin-left:0px;">
                <a class="navbar-brand" asp-area="" asp-controller="Events" asp-action="Index"><img src="https://i.imgur.com/yp2FTzT.png" width="600" height="70" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav" style="margin-left:500px; color:black; font-family:Calibri; font-weight:bolder">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Attendees" asp-action="Index">Attendees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Halls" asp-action="Index">Halls</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted " style="background-color: mintcream">
        <div class="container" style="margin-left:60px">
            &copy; 2021 - Events Hall Management System
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>